/* eslint-disable unicorn/prefer-module */
/* eslint-disable global-require */
const imageIconPack = {
  "@ease": require("@/shared/assets/image/@ease.png"),
  "@ease2": require("@/shared/assets/image/@ease2.png"),
  account: require("@/shared/assets/image/account.png"),
  add: require("@/shared/assets/image/add.png"),
  airtel: require("@/shared/assets/image/airtel.png"),
  airtime: require("@/shared/assets/image/airtime.png"),
  arrowDown: require("@/shared/assets/image/arrowDown.png"),
  arrowLeft: require("@/shared/assets/image/arrowLeft.png"),
  arrowRight: require("@/shared/assets/image/arrowRight.png"),
  atm: require("@/shared/assets/image/atm.png"),
  back: require("@/shared/assets/image/back.png"),
  balance: require("@/shared/assets/image/balance.png"),
  bed: require("@/shared/assets/image/bed.png"),
  calender: require("@/shared/assets/image/calender.png"),
  calendericon: require("@/shared/assets/image/calender.png"),
  centili: require("@/shared/assets/image/centili.png"),
  close: require("@/shared/assets/image/close.png"),
  coins: require("@/shared/assets/image/coins.png"),
  compass: require("@/shared/assets/image/compass.png"),
  complain: require("@/shared/assets/image/complain.png"),
  customer: require("@/shared/assets/image/customer.png"),
  etisalat: require("@/shared/assets/image/9mobile.png"),
  ewallet: require("@/shared/assets/image/eWallet.png"),
  eyeClosed: require("@/shared/assets/image/eye-closed.png"),
  eyeOpen: require("@/shared/assets/image/eye-opened.png"),
  fingerprint: require("@/shared/assets/image/fingerprint.png"),
  flight: require("@/shared/assets/image/flight.png"),
  flights: require("@/shared/assets/image/flights.png"),
  forgotpassword: require("@/shared/assets/image/forgotPassword.png"),
  forward: require("@/shared/assets/image/forward.png"),
  glo: require("@/shared/assets/image/glo.png"),
  history: require("@/shared/assets/image/history.png"),
  home2: require("@/shared/assets/image/home2.png"),
  insurance: require("@/shared/assets/image/insurance.png"),
  landingpagebackground: require("@/shared/assets/image/LandingPageBackground.png"),
  lifestyleBg: require("@/shared/assets/image/lifestyleBg.png"),
  logo: require("@/shared/assets/image/logo.png"),
  mtn: require("@/shared/assets/image/mtn.png"),
  mutualfunds: require("@/shared/assets/image/mutualFunds.png"),
  mybank: require("@/shared/assets/image/myBank.png"),
  payments2: require("@/shared/assets/image/payments2.png"),
  pension: require("@/shared/assets/image/pension.png"),
  plane: require("@/shared/assets/image/plane.png"),
  profile: require("@/shared/assets/image/Profile.png"),
  question: require("@/shared/assets/image/question.png"),
  scheduleicon: require("@/shared/assets/image/scheduleicon.png"),
  search: require("@/shared/assets/image/search.png"),
  star: require("@/shared/assets/image/star.png"),
  stocks: require("@/shared/assets/image/stocks.png"),
  time: require("@/shared/assets/image/time.png"),
  upload: require("@/shared/assets/image/upload.png"),
  user: require("@/shared/assets/image/user.png"),
  users: require("@/shared/assets/image/users.png"),
};

export { imageIconPack };

export type ImageIconPackType = keyof typeof imageIconPack;
