export default [
  "ACCESS BANK PLC",
  "FIRST BANK NIGERIA",
  "GTBANK",
  "STANDARD CHATERED BANK",
  "WEMA BANK",
  "KEYSTONE BANK",
  "UNION BANK",
  "STANBIC IBTC @EASE",
  "PROVIDUS BANK",
  "POLARIS",
  "FIRST CITY MONUMENT BANK",
];
